### ISSUE TITLE
Is the SignBlob API used now deprecated?

### ISSUE THREAD

**Issue by camelpunch** [alexandrubagu/gcs_signed_url#19]
Hi there!

I think that the API endpoint used for signing is [this one](https://cloud.google.com/iam/docs/reference/rest/v1/projects.serviceAccounts/signBlob). If so, this gets turned off on July 1. Any plans to update to [this other one](https://cloud.google.com/iam/docs/reference/credentials/rest/v1/projects.serviceAccounts/signBlob) instead?

If not, I might give it a go.

**Comment by mruoss** [comment]
Hi @camelpunch 
Thanks for the issue, I was not aware of this deprecation. So I'm not currently working on it. If you wanna give it a go, be my guest! Otherwise I will take a look at it. Let me know.

**Comment by mruoss** [comment]
Actually, what makes you think the used api is the deprecated one? I'd have to give it a closer look but after looking at the request and response parameters just briefly, I tkink it's the correct one...

**Comment by camelpunch** [comment]
This comment is what got me worried. https://github.com/alexandrubagu/gcs_signed_url/blob/a02b2bf1bd7bf588a8dfc77256493e7fb63aeb38/lib/gcs_signed_url/crypto.ex#L21

However, this comment points to the new one: https://github.com/alexandrubagu/gcs_signed_url/blob/a02b2bf1bd7bf588a8dfc77256493e7fb63aeb38/lib/gcs_signed_url/sign_blob/http.ex#L3

The actual domain used seems to be content-iamcredentials.googleapis.com - whereas the docs say to use iamcredentials.googleapis.com (this could be deliberate - I don't know enough about this). https://github.com/alexandrubagu/gcs_signed_url/blob/a02b2bf1bd7bf588a8dfc77256493e7fb63aeb38/lib/gcs_signed_url/sign_blob/http.ex#L8

**Comment by mruoss** [comment]
I created a pull request, but have not had time to test it yet.

**Comment by mruoss** [comment]
Fixed. Let me know if you need this released asap. Otherwise with the next release.

**Comment by camelpunch** [comment]
Thanks! It's not urgent for me. I wanted to use this library's parts to sign a direct-upload form POST, but ran into issues with the SignBlob API. I can get an upload working with a static JSON key but the SignBlob API never works.

If I figure it out I might PR form signing into this repo, if that makes sense? Kinda at odds with its name, though.

**Comment by mruoss** [comment]
> We do that on a project. Let me know if you need help with it.

**Comment by camelpunch** [comment]
@mruoss is there any chance I could see a working example of the SignBlob API being used to sign a form upload? I've recently revisited this and come up against the same issues. I tried using the official, generated, google API with the horrendous docs and get the same problems with mismatching sigs.

**Comment by camelpunch** [comment]
My working version with on-premises signing is here: https://github.com/code-supply/code-supply/blob/d10d16df738a799d15b610eb2d7bcbf0e9aa8a0d/web/affable/lib/affable/uploads.ex#L8-L45

It integrates with the fancy LiveView uploads stuff, which needs a JS component: https://github.com/code-supply/code-supply/blob/d10d16df738a799d15b610eb2d7bcbf0e9aa8a0d/web/affable/assets/src/app.ts#L43-L67

**Comment by mruoss** [comment]
Not sure I understand. You have a working solution but you want to switch from on-prem signing to using the API?

**Comment by camelpunch** [comment]
Apologies, I wasn't very clear. Yes! The links above point to working code using on-prem signing. I want to use the SignBlob API, but whenever I use it either from this library or from [Google's SDK](https://hexdocs.pm/google_api_iam_credentials/GoogleApi.IAMCredentials.V1.Api.Projects.html#iamcredentials_projects_service_accounts_sign_blob/5), I run into trouble.

The API returns a base64-encoded string, which differs to the result of the on-prem `sign`, which gives a non-UTF8 bytestring. This would be alright, but even when decoded, the bytes are wildly different from the result of the on-prem signing, and the body of the POST from the browser confirms this (`SignatureDoesNotMatch`).

When I recreate a failing case for the nth time I'll post it as a branch to that code.

**Comment by camelpunch** [comment]
Of course, this time I tried, it worked absolutely fine. I'll post the results in a bit. Thanks for your assistance!

**Comment by camelpunch** [comment]
This is the new working code (missing error checking etc) with SignBlob: https://github.com/code-supply/code-supply/blob/ddcde9e69f5a7098beda4c403483180a261f6372/web/affable/lib/affable/uploads.ex#L33-L50

Thanks for your work!
