### ISSUE TITLE
Remove fixtures in favor of defining local setup blocks

### ISSUE THREAD

**Issue by alexandrubagu** [alexandrubagu/gcs_signed_url#4]
@mruoss I think we can remove fixtures and define local setup blocks. I think is easier to follow what test does in the end.

```elixir
defmodule GcsSignedUrl.CanonicalRequestTest do
  use ExUnit.Case
  alias GcsSignedUrl.CanonicalRequest

  describe "create/4" do
    @signed "content-type;x-foo;x-zed"
    @canonical "content-type:application/json\nx-foo:foo,BA  R,gamma\nx-zed:zed\n"

    setup do
      {:ok, headers: %GcsSignedUrl.Headers{signed: @signed, canonical: @canonical}}
    end

    test "creates canonical request according to specs", %{headers: headers} do
      canonical_request =
        CanonicalRequest.create("GET", "bucket/object.jpg", "foo=bar&alpha=beta", headers)

      assert "GET\nbucket/object.jpg\nfoo=bar&alpha=beta\n#{headers.canonical}\n#{headers.signed}\nUNSIGNED-PAYLOAD" ==
               canonical_request
    end
  end
end

```

WDYT ?

**Comment by mruoss** [comment]
So the reasons I created fixtures:

* They can be shared among tests and don't have to be copy-pasted from test to test.
* They keep the tests cleaner. While I don't see the data at first glance, I see more of what the test does. 

But I am open to discuss it. Why don't you like fixtures or prefer the test data inside tests?

**Comment by mruoss** [comment]
But I guess in most of the cases the data is not shared among tests and with setup blocks it looks clean, too. I did not know about those.

**Comment by alexandrubagu** [comment]
I prefer to use fixtures if data is dynamic generated. For example:
```
generate_public_key()
insert_user(params)
```

**Comment by alexandrubagu** [comment]
I think it's ok if are used in different tests
