### ISSUE TITLE
 GcsSignedUrl.hours_after returns invalid number for v4

### ISSUE THREAD

**Issue by hassanRsiddiqi** [alexandrubagu/gcs_signed_url#59]
`hours_after/1` returns some long number even if you try to get for any number of hours, as per Google [docs](https://cloud.google.com/storage/docs/access-control/signed-urls#should-you-use)  maximum value is 604800 seconds (7 days ) as you can see example below the integers returns by `hours_after` for 3 hours is some big number.
* hours_after should return a valid number of seconds.
```
Erlang/OTP 24 [erts-12.2.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [dtrace]
Interactive Elixir (1.13.0) - press Ctrl+C to exit (type h() ENTER for help)

{:gcs_signed_url, "~> 0.4"},

>>  GcsSignedUrl.hours_after(3)
1649075864
```

**Comment by alexandrubagu** [comment]
```
iex()> DateTime.utc_now() |> DateTime.add(_3_hours_in_seconds = 10800, :second) |> DateTime.to_unix()
1649163984
```

**Comment by hassanRsiddiqi** [comment]
v4 doesn't accept Unix timestamps.

**Comment by hassanRsiddiqi** [comment]
<img width="952" alt="Screenshot 2022-04-05 at 3 12 12 PM" src="https://user-images.githubusercontent.com/23057904/161731848-04ad66ed-5326-46f0-a654-6273f37eb5e1.png">
https://cloud.google.com/storage/docs/access-control/signed-urls

**Comment by mruoss** [comment]
True, thanks for the hint. I will change the readme. However, I don't think we need a function that converts hours to seconds.
