### ISSUE TITLE
GcsSignedUrl.generate_v4 doesn't work

### ISSUE THREAD

**Issue by samee2612** [alexandrubagu/gcs_signed_url#78]
#### Issue description

We have provided correct roles and permissions which are storage bucket creator and ServiceAccountTokenCreator to the service account, still getting 403 permission denied error

Ran the following commands:

{:ok, token} = Goth.Token.fetch(%{})

account="random@gserviceaccount.com"

oauth_config = %GcsSignedUrl.SignBlob.OAuthConfig{service_account: account, access_token: token.token}

GcsSignedUrl.generate_v4(oauth_config, "sample-bucket", "fresh.pdf")
**{:error,
 "403 PERMISSION_DENIED: The caller does not have permission Make sure the authorized SA has role roles/iam.serviceAccountTokenCreator on the SA passed in the URL."}**

**Comment by samee2612** [comment]
This is resolved

**Comment by mruoss** [comment]
It was a config issue, right?

**Comment by samee2612** [comment]
> oken.fetch(%{})

Sorry for delayed response. 
It occurred as the required permissions were not given on the desired project which held that bucket. It worked after the err was fixed through correct permissions assignment.
