### ISSUE TITLE
Tag released package versions

### ISSUE THREAD

**Issue by sgerrand** [alexandrubagu/gcs_signed_url#8]
Thank you for contributing this open source package to the Elixir community. It's very useful and your work on is greatly appreciated.

It would be useful for consumers of this package (like myself) to be able to match versions of this package in [Hex](https://hex.pm) back to the code which was used to publish them. This is additionally valuable when using products like [Dependabot](https://dependabot.com) to automate the process of update dependancies in Elixir projects. Achieving this should be relatively simple, tagging the version control commit which is used to publish the package should be enough.

Adding and using a [changelog](https://keepachangelog.com/en/1.0.0/) on top of tagging package versions would be even better, but I understand that this would add extra work for you.

**Comment by mruoss** [comment]
You're right. Thanks for letting us know. I added releases and a changelog. The changelog only starts from 0.4.0 though.

**Comment by alexandrubagu** [comment]
Thanks @mruoss  ! :+1:
